### PR TITLE
Allow disabling addition of application rules for a list.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
Don't know why postgres doesn't want to play ball.

**Comment by jadb** [comment]
Ugh, not sure why commented there - clicked wrong view :(

**Comment by jadb** [comment]
Postgres been failing all along... Haven't been able to figure out why.

**Comment by ADmad** [comment]
Okay so i dont have to worry about fixing postgres build :P

**Pull request merged**
